import { ProductListItem, ProductDetail } from '../core/models/models';

export const MOCK_PRODUCTS: ProductListItem[] = [
  {
    id: 1,
    title: "Heshe Women's Leather Bag",
    slug: "product-1-heshe-women-s-leather-bag",
    brand: "Heshe",
    gender: "women",
    basePrice: 10399,
    firstImage: "https://cdn.dummyjson.com/product-images/womens-bags/heshe-women's-leather-bag/thumbnail.webp",
    ratingAverage: 3.7,
    ratingCount: 281,
    isFeatured: false,
    categoryName: "Bags & Wallets",
    discountedPrice: 7591,
    mrp: 10399,
    discountPercent: 27
  },
  {
    id: 2,
    title: "Girl Summer Dress",
    slug: "product-2-girl-summer-dress",
    brand: "Style Hub",
    gender: "women",
    basePrice: 1599,
    firstImage: "https://cdn.dummyjson.com/product-images/tops/girl-summer-dress/thumbnail.webp",
    ratingAverage: 3.8,
    ratingCount: 190,
    isFeatured: false,
    categoryName: "Tops & Tees",
    discountedPrice: 1119,
    mrp: 1599,
    discountPercent: 30
  },
  {
    id: 3,
    title: "Blue Frock",
    slug: "product-3-blue-frock",
    brand: "Style Hub",
    gender: "women",
    basePrice: 2399,
    firstImage: "https://cdn.dummyjson.com/product-images/tops/blue-frock/thumbnail.webp",
    ratingAverage: 4.8,
    ratingCount: 56,
    isFeatured: false,
    categoryName: "Tops & Tees",
    discountedPrice: 1223,
    mrp: 2399,
    discountPercent: 49
  },
  {
    id: 4,
    title: "Blue Women's Handbag",
    slug: "product-4-blue-women-s-handbag",
    brand: "Fashionista",
    gender: "women",
    basePrice: 3999,
    firstImage: "https://cdn.dummyjson.com/product-images/womens-bags/blue-women's-handbag/thumbnail.webp",
    ratingAverage: 4.2,
    ratingCount: 39,
    isFeatured: false,
    categoryName: "Bags & Wallets",
    discountedPrice: 3239,
    mrp: 3999,
    discountPercent: 19
  },
  {
    id: 5,
    title: "Short Frock",
    slug: "product-5-short-frock",
    brand: "Style Hub",
    gender: "women",
    basePrice: 1999,
    firstImage: "https://cdn.dummyjson.com/product-images/tops/short-frock/thumbnail.webp",
    ratingAverage: 3.9,
    ratingCount: 35,
    isFeatured: false,
    categoryName: "Tops & Tees",
    discountedPrice: 1459,
    mrp: 1999,
    discountPercent: 27
  },
  {
    id: 6,
    title: "Golden Shoes Woman",
    slug: "product-6-golden-shoes-woman",
    brand: "Fashion Diva",
    gender: "women",
    basePrice: 3999,
    firstImage: "https://cdn.dummyjson.com/product-images/womens-shoes/golden-shoes-woman/thumbnail.webp",
    ratingAverage: 3.9,
    ratingCount: 192,
    isFeatured: true,
    categoryName: "Sandals & Flats",
    discountedPrice: 3399,
    mrp: 3999,
    discountPercent: 15
  },
  {
    id: 7,
    title: "Watch Gold for Women",
    slug: "product-7-watch-gold-for-women",
    brand: "Fashion Gold",
    gender: "women",
    basePrice: 63999,
    firstImage: "https://cdn.dummyjson.com/product-images/womens-watches/watch-gold-for-women/thumbnail.webp",
    ratingAverage: 4.3,
    ratingCount: 53,
    isFeatured: false,
    categoryName: "Watches",
    discountedPrice: 55039,
    mrp: 63999,
    discountPercent: 14
  },
  {
    id: 8,
    title: "Green Oval Earring",
    slug: "product-8-green-oval-earring",
    brand: "Style Hub",
    gender: "women",
    basePrice: 1999,
    firstImage: "https://cdn.dummyjson.com/product-images/womens-jewellery/green-oval-earring/thumbnail.webp",
    ratingAverage: 3.6,
    ratingCount: 232,
    isFeatured: true,
    categoryName: "Jewellery",
    discountedPrice: 1459,
    mrp: 1999,
    discountPercent: 27
  },
  {
    id: 9,
    title: "White Faux Leather Backpack",
    slug: "product-9-white-faux-leather-backpack",
    brand: "Urban Chic",
    gender: "women",
    basePrice: 3199,
    firstImage: "https://cdn.dummyjson.com/product-images/womens-bags/white-faux-leather-backpack/thumbnail.webp",
    ratingAverage: 4.8,
    ratingCount: 184,
    isFeatured: false,
    categoryName: "Bags & Wallets",
    discountedPrice: 2079,
    mrp: 3199,
    discountPercent: 35
  },
  {
    id: 10,
    title: "Women's Wrist Watch",
    slug: "product-10-women-s-wrist-watch",
    brand: "Fashion Co.",
    gender: "women",
    basePrice: 10399,
    firstImage: "https://cdn.dummyjson.com/product-images/womens-watches/women's-wrist-watch/thumbnail.webp",
    ratingAverage: 4.6,
    ratingCount: 207,
    isFeatured: false,
    categoryName: "Watches",
    discountedPrice: 7071,
    mrp: 10399,
    discountPercent: 32
  },
  {
    id: 11,
    title: "Calvin Klein Heel Shoes",
    slug: "product-11-calvin-klein-heel-shoes",
    brand: "Calvin Klein",
    gender: "women",
    basePrice: 6399,
    firstImage: "https://cdn.dummyjson.com/product-images/womens-shoes/calvin-klein-heel-shoes/thumbnail.webp",
    ratingAverage: 4.5,
    ratingCount: 83,
    isFeatured: true,
    categoryName: "Sandals & Flats",
    discountedPrice: 3967,
    mrp: 6399,
    discountPercent: 38
  },
  {
    id: 12,
    title: "Corset Leather With Skirt",
    slug: "product-12-corset-leather-with-skirt",
    brand: "Style Hub",
    gender: "women",
    basePrice: 7199,
    firstImage: "https://cdn.dummyjson.com/product-images/womens-dresses/corset-leather-with-skirt/thumbnail.webp",
    ratingAverage: 4.2,
    ratingCount: 269,
    isFeatured: false,
    categoryName: "Dresses",
    discountedPrice: 4463,
    mrp: 7199,
    discountPercent: 38
  },
  {
    id: 13,
    title: "Black & Brown Slipper",
    slug: "product-13-black-brown-slipper",
    brand: "Comfort Trends",
    gender: "women",
    basePrice: 1599,
    firstImage: "https://cdn.dummyjson.com/product-images/womens-shoes/black-&-brown-slipper/thumbnail.webp",
    ratingAverage: 3.7,
    ratingCount: 177,
    isFeatured: false,
    categoryName: "Sandals & Flats",
    discountedPrice: 895,
    mrp: 1599,
    discountPercent: 44
  },
  {
    id: 14,
    title: "Women Handbag Black",
    slug: "product-14-women-handbag-black",
    brand: "Elegance Collection",
    gender: "women",
    basePrice: 4799,
    firstImage: "https://cdn.dummyjson.com/product-images/womens-bags/women-handbag-black/thumbnail.webp",
    ratingAverage: 4,
    ratingCount: 155,
    isFeatured: false,
    categoryName: "Bags & Wallets",
    discountedPrice: 3695,
    mrp: 4799,
    discountPercent: 23
  },
  {
    id: 15,
    title: "Gray Dress",
    slug: "product-15-gray-dress",
    brand: "Style Hub",
    gender: "women",
    basePrice: 2799,
    firstImage: "https://cdn.dummyjson.com/product-images/tops/gray-dress/thumbnail.webp",
    ratingAverage: 4.5,
    ratingCount: 275,
    isFeatured: false,
    categoryName: "Tops & Tees",
    discountedPrice: 1875,
    mrp: 2799,
    discountPercent: 33
  },
  {
    id: 16,
    title: "Pampi Shoes",
    slug: "product-16-pampi-shoes",
    brand: "Pampi",
    gender: "women",
    basePrice: 2399,
    firstImage: "https://cdn.dummyjson.com/product-images/womens-shoes/pampi-shoes/thumbnail.webp",
    ratingAverage: 3.8,
    ratingCount: 183,
    isFeatured: false,
    categoryName: "Sandals & Flats",
    discountedPrice: 1535,
    mrp: 2399,
    discountPercent: 36
  },
  {
    id: 17,
    title: "Tartan Dress",
    slug: "product-17-tartan-dress",
    brand: "Style Hub",
    gender: "women",
    basePrice: 3199,
    firstImage: "https://cdn.dummyjson.com/product-images/tops/tartan-dress/thumbnail.webp",
    ratingAverage: 5,
    ratingCount: 302,
    isFeatured: false,
    categoryName: "Tops & Tees",
    discountedPrice: 1983,
    mrp: 3199,
    discountPercent: 38
  },
  {
    id: 18,
    title: "IWC Ingenieur Automatic Steel",
    slug: "product-18-iwc-ingenieur-automatic-steel",
    brand: "IWC",
    gender: "women",
    basePrice: 399999,
    firstImage: "https://cdn.dummyjson.com/product-images/womens-watches/iwc-ingenieur-automatic-steel/thumbnail.webp",
    ratingAverage: 4.4,
    ratingCount: 40,
    isFeatured: true,
    categoryName: "Watches",
    discountedPrice: 327999,
    mrp: 399999,
    discountPercent: 18
  },
  {
    id: 19,
    title: "Prada Women Bag",
    slug: "product-19-prada-women-bag",
    brand: "Prada",
    gender: "women",
    basePrice: 47999,
    firstImage: "https://cdn.dummyjson.com/product-images/womens-bags/prada-women-bag/thumbnail.webp",
    ratingAverage: 4.4,
    ratingCount: 67,
    isFeatured: false,
    categoryName: "Bags & Wallets",
    discountedPrice: 43199,
    mrp: 47999,
    discountPercent: 10
  },
  {
    id: 20,
    title: "Black Women's Gown",
    slug: "product-20-black-women-s-gown",
    brand: "Style Hub",
    gender: "women",
    basePrice: 10399,
    firstImage: "https://cdn.dummyjson.com/product-images/womens-dresses/black-women's-gown/thumbnail.webp",
    ratingAverage: 3.5,
    ratingCount: 137,
    isFeatured: false,
    categoryName: "Dresses",
    discountedPrice: 8007,
    mrp: 10399,
    discountPercent: 23
  },
  {
    id: 21,
    title: "Blue & Black Check Shirt",
    slug: "product-21-blue-black-check-shirt",
    brand: "Fashion Trends",
    gender: "men",
    basePrice: 2399,
    firstImage: "https://cdn.dummyjson.com/product-images/mens-shirts/blue-&-black-check-shirt/thumbnail.webp",
    ratingAverage: 4.9,
    ratingCount: 80,
    isFeatured: false,
    categoryName: "Shirts",
    discountedPrice: 1823,
    mrp: 2399,
    discountPercent: 24
  },
  {
    id: 22,
    title: "Man Plaid Shirt",
    slug: "product-22-man-plaid-shirt",
    brand: "Classic Wear",
    gender: "men",
    basePrice: 2799,
    firstImage: "https://cdn.dummyjson.com/product-images/mens-shirts/man-plaid-shirt/thumbnail.webp",
    ratingAverage: 4.3,
    ratingCount: 66,
    isFeatured: false,
    categoryName: "Shirts",
    discountedPrice: 1931,
    mrp: 2799,
    discountPercent: 31
  },
  {
    id: 23,
    title: "Rolex Cellini Moonphase",
    slug: "product-23-rolex-cellini-moonphase",
    brand: "Rolex",
    gender: "men",
    basePrice: 1039999,
    firstImage: "https://cdn.dummyjson.com/product-images/mens-watches/rolex-cellini-moonphase/thumbnail.webp",
    ratingAverage: 4,
    ratingCount: 274,
    isFeatured: false,
    categoryName: "Watches",
    discountedPrice: 904799,
    mrp: 1039999,
    discountPercent: 13
  },
  {
    id: 24,
    title: "Sports Sneakers Off White Red",
    slug: "product-24-sports-sneakers-off-white-red",
    brand: "Off White",
    gender: "men",
    basePrice: 8799,
    firstImage: "https://cdn.dummyjson.com/product-images/mens-shoes/sports-sneakers-off-white-red/thumbnail.webp",
    ratingAverage: 3.8,
    ratingCount: 73,
    isFeatured: false,
    categoryName: "Sneakers",
    discountedPrice: 6511,
    mrp: 8799,
    discountPercent: 26
  },
  {
    id: 25,
    title: "Puma Future Rider Trainers",
    slug: "product-25-puma-future-rider-trainers",
    brand: "Puma",
    gender: "men",
    basePrice: 7199,
    firstImage: "https://cdn.dummyjson.com/product-images/mens-shoes/puma-future-rider-trainers/thumbnail.webp",
    ratingAverage: 4.8,
    ratingCount: 294,
    isFeatured: false,
    categoryName: "Sneakers",
    discountedPrice: 4535,
    mrp: 7199,
    discountPercent: 37
  },
  {
    id: 26,
    title: "Rolex Submariner Watch",
    slug: "product-26-rolex-submariner-watch",
    brand: "Rolex",
    gender: "men",
    basePrice: 1119999,
    firstImage: "https://cdn.dummyjson.com/product-images/mens-watches/rolex-submariner-watch/thumbnail.webp",
    ratingAverage: 4.9,
    ratingCount: 285,
    isFeatured: false,
    categoryName: "Watches",
    discountedPrice: 615999,
    mrp: 1119999,
    discountPercent: 45
  },
  {
    id: 27,
    title: "Nike Air Jordan 1 Red And Black",
    slug: "product-27-nike-air-jordan-1-red-and-black",
    brand: "Nike",
    gender: "men",
    basePrice: 11999,
    firstImage: "https://cdn.dummyjson.com/product-images/mens-shoes/nike-air-jordan-1-red-and-black/thumbnail.webp",
    ratingAverage: 4,
    ratingCount: 195,
    isFeatured: true,
    categoryName: "Sneakers",
    discountedPrice: 7799,
    mrp: 11999,
    discountPercent: 35
  },
  {
    id: 28,
    title: "Gigabyte Aorus Men Tshirt",
    slug: "product-28-gigabyte-aorus-men-tshirt",
    brand: "Gigabyte",
    gender: "men",
    basePrice: 1999,
    firstImage: "https://cdn.dummyjson.com/product-images/mens-shirts/gigabyte-aorus-men-tshirt/thumbnail.webp",
    ratingAverage: 4.8,
    ratingCount: 292,
    isFeatured: false,
    categoryName: "Shirts",
    discountedPrice: 1759,
    mrp: 1999,
    discountPercent: 12
  },
  {
    id: 29,
    title: "Brown Leather Belt Watch",
    slug: "product-29-brown-leather-belt-watch",
    brand: "Fashion Timepieces",
    gender: "men",
    basePrice: 7199,
    firstImage: "https://images.unsplash.com/photo-1524805444758-089113d48a6d?w=400",
    ratingAverage: 4.3,
    ratingCount: 275,
    isFeatured: false,
    categoryName: "Watches",
    discountedPrice: 4895,
    mrp: 7199,
    discountPercent: 32
  },
  {
    id: 30,
    title: "Man Short Sleeve Shirt",
    slug: "product-30-man-short-sleeve-shirt",
    brand: "Casual Comfort",
    gender: "men",
    basePrice: 1599,
    firstImage: "https://cdn.dummyjson.com/product-images/mens-shirts/man-short-sleeve-shirt/thumbnail.webp",
    ratingAverage: 5,
    ratingCount: 152,
    isFeatured: false,
    categoryName: "Shirts",
    discountedPrice: 1407,
    mrp: 1599,
    discountPercent: 12
  },
  {
    id: 31,
    title: "Men Check Shirt",
    slug: "product-31-men-check-shirt",
    brand: "Urban Chic",
    gender: "men",
    basePrice: 2239,
    firstImage: "https://cdn.dummyjson.com/product-images/mens-shirts/men-check-shirt/thumbnail.webp",
    ratingAverage: 3.5,
    ratingCount: 228,
    isFeatured: true,
    categoryName: "Shirts",
    discountedPrice: 1186,
    mrp: 2239,
    discountPercent: 47
  },
  {
    id: 32,
    title: "Rolex Datejust",
    slug: "product-32-rolex-datejust",
    brand: "Rolex",
    gender: "men",
    basePrice: 879999,
    firstImage: "https://cdn.dummyjson.com/product-images/mens-watches/rolex-datejust/thumbnail.webp",
    ratingAverage: 4.5,
    ratingCount: 25,
    isFeatured: false,
    categoryName: "Watches",
    discountedPrice: 589599,
    mrp: 879999,
    discountPercent: 33
  },
  {
    id: 33,
    title: "Sports Sneakers Off White & Red",
    slug: "product-33-sports-sneakers-off-white-red",
    brand: "Off White",
    gender: "men",
    basePrice: 9599,
    firstImage: "https://cdn.dummyjson.com/product-images/mens-shoes/sports-sneakers-off-white-&-red/thumbnail.webp",
    ratingAverage: 3.7,
    ratingCount: 201,
    isFeatured: false,
    categoryName: "Sneakers",
    discountedPrice: 7871,
    mrp: 9599,
    discountPercent: 18
  },
  {
    id: 34,
    title: "Longines Master Collection",
    slug: "product-34-longines-master-collection",
    brand: "Longines",
    gender: "men",
    basePrice: 119999,
    firstImage: "https://cdn.dummyjson.com/product-images/mens-watches/longines-master-collection/thumbnail.webp",
    ratingAverage: 3.9,
    ratingCount: 61,
    isFeatured: false,
    categoryName: "Watches",
    discountedPrice: 75599,
    mrp: 119999,
    discountPercent: 37
  },
  {
    id: 35,
    title: "Rolex Cellini Date Black Dial",
    slug: "product-35-rolex-cellini-date-black-dial",
    brand: "Rolex",
    gender: "men",
    basePrice: 719999,
    firstImage: "https://cdn.dummyjson.com/product-images/mens-watches/rolex-cellini-date-black-dial/thumbnail.webp",
    ratingAverage: 3.9,
    ratingCount: 299,
    isFeatured: false,
    categoryName: "Watches",
    discountedPrice: 467999,
    mrp: 719999,
    discountPercent: 35
  },
  {
    id: 36,
    title: "Nike Baseball Cleats",
    slug: "product-36-nike-baseball-cleats",
    brand: "Nike",
    gender: "men",
    basePrice: 6399,
    firstImage: "https://cdn.dummyjson.com/product-images/mens-shoes/nike-baseball-cleats/thumbnail.webp",
    ratingAverage: 4.9,
    ratingCount: 85,
    isFeatured: false,
    categoryName: "Sneakers",
    discountedPrice: 3647,
    mrp: 6399,
    discountPercent: 43
  },
  {
    id: 37,
    title: "Blue & Black Check Shirt",
    slug: "product-37-blue-black-check-shirt",
    brand: "Fashion Trends",
    gender: "men",
    basePrice: 2399,
    firstImage: "https://cdn.dummyjson.com/product-images/mens-shirts/blue-&-black-check-shirt/thumbnail.webp",
    ratingAverage: 4.8,
    ratingCount: 154,
    isFeatured: false,
    categoryName: "Shirts",
    discountedPrice: 2063,
    mrp: 2399,
    discountPercent: 14
  },
  {
    id: 38,
    title: "Man Plaid Shirt",
    slug: "product-38-man-plaid-shirt",
    brand: "Classic Wear",
    gender: "men",
    basePrice: 2799,
    firstImage: "https://cdn.dummyjson.com/product-images/mens-shirts/man-plaid-shirt/thumbnail.webp",
    ratingAverage: 3.8,
    ratingCount: 208,
    isFeatured: true,
    categoryName: "Shirts",
    discountedPrice: 1511,
    mrp: 2799,
    discountPercent: 46
  },
  {
    id: 39,
    title: "Rolex Cellini Moonphase",
    slug: "product-39-rolex-cellini-moonphase",
    brand: "Rolex",
    gender: "men",
    basePrice: 1039999,
    firstImage: "https://cdn.dummyjson.com/product-images/mens-watches/rolex-cellini-moonphase/thumbnail.webp",
    ratingAverage: 4,
    ratingCount: 218,
    isFeatured: false,
    categoryName: "Watches",
    discountedPrice: 821599,
    mrp: 1039999,
    discountPercent: 21
  },
  {
    id: 40,
    title: "Sports Sneakers Off White Red",
    slug: "product-40-sports-sneakers-off-white-red",
    brand: "Off White",
    gender: "men",
    basePrice: 8799,
    firstImage: "https://cdn.dummyjson.com/product-images/mens-shoes/sports-sneakers-off-white-red/thumbnail.webp",
    ratingAverage: 3.6,
    ratingCount: 37,
    isFeatured: false,
    categoryName: "Sneakers",
    discountedPrice: 4575,
    mrp: 8799,
    discountPercent: 48
  },
  {
    id: 41,
    title: "Sunglasses",
    slug: "product-41-sunglasses",
    brand: "Fashion Shades",
    gender: "unisex",
    basePrice: 1839,
    firstImage: "https://cdn.dummyjson.com/product-images/sunglasses/sunglasses/thumbnail.webp",
    ratingAverage: 4.5,
    ratingCount: 116,
    isFeatured: true,
    categoryName: "Sunglasses",
    discountedPrice: 1342,
    mrp: 1839,
    discountPercent: 27
  },
  {
    id: 42,
    title: "Party Glasses",
    slug: "product-42-party-glasses",
    brand: "Fashion Fun",
    gender: "unisex",
    basePrice: 1599,
    firstImage: "https://cdn.dummyjson.com/product-images/sunglasses/party-glasses/thumbnail.webp",
    ratingAverage: 4,
    ratingCount: 163,
    isFeatured: false,
    categoryName: "Sunglasses",
    discountedPrice: 1151,
    mrp: 1599,
    discountPercent: 28
  },
  {
    id: 43,
    title: "Green and Black Glasses",
    slug: "product-43-green-and-black-glasses",
    brand: "Fashion Shades",
    gender: "unisex",
    basePrice: 2799,
    firstImage: "https://cdn.dummyjson.com/product-images/sunglasses/green-and-black-glasses/thumbnail.webp",
    ratingAverage: 4.2,
    ratingCount: 122,
    isFeatured: false,
    categoryName: "Sunglasses",
    discountedPrice: 1819,
    mrp: 2799,
    discountPercent: 35
  },
  {
    id: 44,
    title: "Classic Sun Glasses",
    slug: "product-44-classic-sun-glasses",
    brand: "Fashion Shades",
    gender: "unisex",
    basePrice: 1999,
    firstImage: "https://cdn.dummyjson.com/product-images/sunglasses/classic-sun-glasses/thumbnail.webp",
    ratingAverage: 4.2,
    ratingCount: 23,
    isFeatured: false,
    categoryName: "Sunglasses",
    discountedPrice: 1219,
    mrp: 1999,
    discountPercent: 39
  },
  {
    id: 45,
    title: "Black Sun Glasses",
    slug: "product-45-black-sun-glasses",
    brand: "Fashion Shades",
    gender: "unisex",
    basePrice: 2399,
    firstImage: "https://cdn.dummyjson.com/product-images/sunglasses/black-sun-glasses/thumbnail.webp",
    ratingAverage: 3.6,
    ratingCount: 67,
    isFeatured: false,
    categoryName: "Sunglasses",
    discountedPrice: 1919,
    mrp: 2399,
    discountPercent: 20
  },
  {
    id: 46,
    title: "Sunglasses",
    slug: "product-46-sunglasses",
    brand: "Fashion Shades",
    gender: "unisex",
    basePrice: 1839,
    firstImage: "https://cdn.dummyjson.com/product-images/sunglasses/sunglasses/thumbnail.webp",
    ratingAverage: 4.7,
    ratingCount: 250,
    isFeatured: false,
    categoryName: "Sunglasses",
    discountedPrice: 1544,
    mrp: 1839,
    discountPercent: 16
  },
  {
    id: 47,
    title: "Party Glasses",
    slug: "product-47-party-glasses",
    brand: "Fashion Fun",
    gender: "unisex",
    basePrice: 1599,
    firstImage: "https://cdn.dummyjson.com/product-images/sunglasses/party-glasses/thumbnail.webp",
    ratingAverage: 4.9,
    ratingCount: 207,
    isFeatured: true,
    categoryName: "Sunglasses",
    discountedPrice: 975,
    mrp: 1599,
    discountPercent: 39
  },
  {
    id: 48,
    title: "Green and Black Glasses",
    slug: "product-48-green-and-black-glasses",
    brand: "Fashion Shades",
    gender: "unisex",
    basePrice: 2799,
    firstImage: "https://cdn.dummyjson.com/product-images/sunglasses/green-and-black-glasses/thumbnail.webp",
    ratingAverage: 4.2,
    ratingCount: 21,
    isFeatured: false,
    categoryName: "Sunglasses",
    discountedPrice: 1679,
    mrp: 2799,
    discountPercent: 40
  },
  {
    id: 49,
    title: "Classic Sun Glasses",
    slug: "product-49-classic-sun-glasses",
    brand: "Fashion Shades",
    gender: "unisex",
    basePrice: 1999,
    firstImage: "https://cdn.dummyjson.com/product-images/sunglasses/classic-sun-glasses/thumbnail.webp",
    ratingAverage: 4.6,
    ratingCount: 158,
    isFeatured: false,
    categoryName: "Sunglasses",
    discountedPrice: 1739,
    mrp: 1999,
    discountPercent: 13
  },
  {
    id: 50,
    title: "Black Sun Glasses",
    slug: "product-50-black-sun-glasses",
    brand: "Fashion Shades",
    gender: "unisex",
    basePrice: 2399,
    firstImage: "https://cdn.dummyjson.com/product-images/sunglasses/black-sun-glasses/thumbnail.webp",
    ratingAverage: 3.5,
    ratingCount: 59,
    isFeatured: false,
    categoryName: "Sunglasses",
    discountedPrice: 1415,
    mrp: 2399,
    discountPercent: 41
  }
];

export const MOCK_PRODUCTS_DETAIL: ProductDetail[] = [
  {
    "id": 1,
    "title": "Heshe Women's Leather Bag",
    "slug": "product-1-heshe-women-s-leather-bag",
    "brand": "Heshe",
    "gender": "women",
    "basePrice": 10399,
    "firstImage": "https://cdn.dummyjson.com/product-images/womens-bags/heshe-women's-leather-bag/thumbnail.webp",
    "ratingAverage": 3.7,
    "ratingCount": 281,
    "isFeatured": false,
    "categoryName": "Bags & Wallets",
    "discountedPrice": 7591,
    "mrp": 10399,
    "discountPercent": 27,
    "description": "The Heshe Women's Leather Bag is a luxurious and high-quality leather bag for the sophisticated woman. With a timeless design and durable craftsmanship, it's a versatile accessory.",
    "images": [
      "https://cdn.dummyjson.com/product-images/womens-bags/heshe-women's-leather-bag/1.webp",
      "https://cdn.dummyjson.com/product-images/womens-bags/heshe-women's-leather-bag/2.webp",
      "https://cdn.dummyjson.com/product-images/womens-bags/heshe-women's-leather-bag/3.webp"
    ]
  },
  {
    "id": 2,
    "title": "Girl Summer Dress",
    "slug": "product-2-girl-summer-dress",
    "brand": "Style Hub",
    "gender": "women",
    "basePrice": 1599,
    "firstImage": "https://cdn.dummyjson.com/product-images/tops/girl-summer-dress/thumbnail.webp",
    "ratingAverage": 3.8,
    "ratingCount": 190,
    "isFeatured": false,
    "categoryName": "Tops & Tees",
    "discountedPrice": 1119,
    "mrp": 1599,
    "discountPercent": 30,
    "description": "The Girl Summer Dress is a cute and breezy dress designed for warm weather. With playful patterns and lightweight fabric, it's perfect for keeping cool and stylish during the summer.",
    "images": [
      "https://cdn.dummyjson.com/product-images/tops/girl-summer-dress/1.webp",
      "https://cdn.dummyjson.com/product-images/tops/girl-summer-dress/2.webp",
      "https://cdn.dummyjson.com/product-images/tops/girl-summer-dress/3.webp",
      "https://cdn.dummyjson.com/product-images/tops/girl-summer-dress/4.webp"
    ]
  },
  {
    "id": 3,
    "title": "Blue Frock",
    "slug": "product-3-blue-frock",
    "brand": "Style Hub",
    "gender": "women",
    "basePrice": 2399,
    "firstImage": "https://cdn.dummyjson.com/product-images/tops/blue-frock/thumbnail.webp",
    "ratingAverage": 4.8,
    "ratingCount": 56,
    "isFeatured": false,
    "categoryName": "Tops & Tees",
    "discountedPrice": 1223,
    "mrp": 2399,
    "discountPercent": 49,
    "description": "The Blue Frock is a charming and stylish dress for various occasions. With a vibrant blue color and a comfortable design, it adds a touch of elegance to your wardrobe.",
    "images": [
      "https://cdn.dummyjson.com/product-images/tops/blue-frock/1.webp",
      "https://cdn.dummyjson.com/product-images/tops/blue-frock/2.webp",
      "https://cdn.dummyjson.com/product-images/tops/blue-frock/3.webp",
      "https://cdn.dummyjson.com/product-images/tops/blue-frock/4.webp"
    ]
  },
  {
    "id": 4,
    "title": "Blue Women's Handbag",
    "slug": "product-4-blue-women-s-handbag",
    "brand": "Fashionista",
    "gender": "women",
    "basePrice": 3999,
    "firstImage": "https://cdn.dummyjson.com/product-images/womens-bags/blue-women's-handbag/thumbnail.webp",
    "ratingAverage": 4.2,
    "ratingCount": 39,
    "isFeatured": false,
    "categoryName": "Bags & Wallets",
    "discountedPrice": 3239,
    "mrp": 3999,
    "discountPercent": 19,
    "description": "The Blue Women's Handbag is a stylish and spacious accessory for everyday use. With a vibrant blue color and multiple compartments, it combines fashion and functionality.",
    "images": [
      "https://cdn.dummyjson.com/product-images/womens-bags/blue-women's-handbag/1.webp",
      "https://cdn.dummyjson.com/product-images/womens-bags/blue-women's-handbag/2.webp",
      "https://cdn.dummyjson.com/product-images/womens-bags/blue-women's-handbag/3.webp"
    ]
  },
  {
    "id": 5,
    "title": "Short Frock",
    "slug": "product-5-short-frock",
    "brand": "Style Hub",
    "gender": "women",
    "basePrice": 1999,
    "firstImage": "https://cdn.dummyjson.com/product-images/tops/short-frock/thumbnail.webp",
    "ratingAverage": 3.9,
    "ratingCount": 35,
    "isFeatured": false,
    "categoryName": "Tops & Tees",
    "discountedPrice": 1459,
    "mrp": 1999,
    "discountPercent": 27,
    "description": "The Short Frock is a playful and trendy dress with a shorter length. Ideal for casual outings or special occasions, it combines style and comfort for a fashionable look.",
    "images": [
      "https://cdn.dummyjson.com/product-images/tops/short-frock/1.webp",
      "https://cdn.dummyjson.com/product-images/tops/short-frock/2.webp",
      "https://cdn.dummyjson.com/product-images/tops/short-frock/3.webp",
      "https://cdn.dummyjson.com/product-images/tops/short-frock/4.webp"
    ]
  },
  {
    "id": 6,
    "title": "Golden Shoes Woman",
    "slug": "product-6-golden-shoes-woman",
    "brand": "Fashion Diva",
    "gender": "women",
    "basePrice": 3999,
    "firstImage": "https://cdn.dummyjson.com/product-images/womens-shoes/golden-shoes-woman/thumbnail.webp",
    "ratingAverage": 3.9,
    "ratingCount": 192,
    "isFeatured": true,
    "categoryName": "Sandals & Flats",
    "discountedPrice": 3399,
    "mrp": 3999,
    "discountPercent": 15,
    "description": "The Golden Shoes for Women are a glamorous choice for special occasions. Featuring a golden hue and stylish design, they add a touch of luxury to your outfit.",
    "images": [
      "https://cdn.dummyjson.com/product-images/womens-shoes/golden-shoes-woman/1.webp",
      "https://cdn.dummyjson.com/product-images/womens-shoes/golden-shoes-woman/2.webp",
      "https://cdn.dummyjson.com/product-images/womens-shoes/golden-shoes-woman/3.webp",
      "https://cdn.dummyjson.com/product-images/womens-shoes/golden-shoes-woman/4.webp"
    ]
  },
  {
    "id": 7,
    "title": "Watch Gold for Women",
    "slug": "product-7-watch-gold-for-women",
    "brand": "Fashion Gold",
    "gender": "women",
    "basePrice": 63999,
    "firstImage": "https://cdn.dummyjson.com/product-images/womens-watches/watch-gold-for-women/thumbnail.webp",
    "ratingAverage": 4.3,
    "ratingCount": 53,
    "isFeatured": false,
    "categoryName": "Watches",
    "discountedPrice": 55039,
    "mrp": 63999,
    "discountPercent": 14,
    "description": "The Gold Women's Watch is a stunning accessory that combines luxury and style. Featuring a gold-plated case and a chic design, it adds a touch of glamour to any outfit.",
    "images": [
      "https://cdn.dummyjson.com/product-images/womens-watches/watch-gold-for-women/1.webp",
      "https://cdn.dummyjson.com/product-images/womens-watches/watch-gold-for-women/2.webp",
      "https://cdn.dummyjson.com/product-images/womens-watches/watch-gold-for-women/3.webp"
    ]
  },
  {
    "id": 8,
    "title": "Green Oval Earring",
    "slug": "product-8-green-oval-earring",
    "brand": "Style Hub",
    "gender": "women",
    "basePrice": 1999,
    "firstImage": "https://cdn.dummyjson.com/product-images/womens-jewellery/green-oval-earring/thumbnail.webp",
    "ratingAverage": 3.6,
    "ratingCount": 232,
    "isFeatured": true,
    "categoryName": "Jewellery",
    "discountedPrice": 1459,
    "mrp": 1999,
    "discountPercent": 27,
    "description": "The Green Oval Earring is a stylish and versatile accessory with a unique oval shape. Whether for casual or dressy occasions, its green hue and contemporary design make it a standout piece.",
    "images": [
      "https://cdn.dummyjson.com/product-images/womens-jewellery/green-oval-earring/1.webp",
      "https://cdn.dummyjson.com/product-images/womens-jewellery/green-oval-earring/2.webp",
      "https://cdn.dummyjson.com/product-images/womens-jewellery/green-oval-earring/3.webp"
    ]
  },
  {
    "id": 9,
    "title": "White Faux Leather Backpack",
    "slug": "product-9-white-faux-leather-backpack",
    "brand": "Urban Chic",
    "gender": "women",
    "basePrice": 3199,
    "firstImage": "https://cdn.dummyjson.com/product-images/womens-bags/white-faux-leather-backpack/thumbnail.webp",
    "ratingAverage": 4.8,
    "ratingCount": 184,
    "isFeatured": false,
    "categoryName": "Bags & Wallets",
    "discountedPrice": 2079,
    "mrp": 3199,
    "discountPercent": 35,
    "description": "The White Faux Leather Backpack is a trendy and practical backpack for the modern woman. With a sleek white design and ample storage space, it's perfect for both casual and on-the-go styles.",
    "images": [
      "https://cdn.dummyjson.com/product-images/womens-bags/white-faux-leather-backpack/1.webp",
      "https://cdn.dummyjson.com/product-images/womens-bags/white-faux-leather-backpack/2.webp",
      "https://cdn.dummyjson.com/product-images/womens-bags/white-faux-leather-backpack/3.webp"
    ]
  },
  {
    "id": 10,
    "title": "Women's Wrist Watch",
    "slug": "product-10-women-s-wrist-watch",
    "brand": "Fashion Co.",
    "gender": "women",
    "basePrice": 10399,
    "firstImage": "https://cdn.dummyjson.com/product-images/womens-watches/women's-wrist-watch/thumbnail.webp",
    "ratingAverage": 4.6,
    "ratingCount": 207,
    "isFeatured": false,
    "categoryName": "Watches",
    "discountedPrice": 7071,
    "mrp": 10399,
    "discountPercent": 32,
    "description": "The Women's Wrist Watch is a versatile and fashionable timepiece for everyday wear. With a comfortable strap and a simple yet elegant design, it complements various styles.",
    "images": [
      "https://cdn.dummyjson.com/product-images/womens-watches/women's-wrist-watch/1.webp",
      "https://cdn.dummyjson.com/product-images/womens-watches/women's-wrist-watch/2.webp",
      "https://cdn.dummyjson.com/product-images/womens-watches/women's-wrist-watch/3.webp"
    ]
  },
  {
    "id": 11,
    "title": "Calvin Klein Heel Shoes",
    "slug": "product-11-calvin-klein-heel-shoes",
    "brand": "Calvin Klein",
    "gender": "women",
    "basePrice": 6399,
    "firstImage": "https://cdn.dummyjson.com/product-images/womens-shoes/calvin-klein-heel-shoes/thumbnail.webp",
    "ratingAverage": 4.5,
    "ratingCount": 83,
    "isFeatured": true,
    "categoryName": "Sandals & Flats",
    "discountedPrice": 3967,
    "mrp": 6399,
    "discountPercent": 38,
    "description": "Calvin Klein Heel Shoes are elegant and sophisticated, designed for formal occasions. With a classic design and high-quality materials, they complement your stylish ensemble.",
    "images": [
      "https://cdn.dummyjson.com/product-images/womens-shoes/calvin-klein-heel-shoes/1.webp",
      "https://cdn.dummyjson.com/product-images/womens-shoes/calvin-klein-heel-shoes/2.webp",
      "https://cdn.dummyjson.com/product-images/womens-shoes/calvin-klein-heel-shoes/3.webp",
      "https://cdn.dummyjson.com/product-images/womens-shoes/calvin-klein-heel-shoes/4.webp"
    ]
  },
  {
    "id": 12,
    "title": "Corset Leather With Skirt",
    "slug": "product-12-corset-leather-with-skirt",
    "brand": "Style Hub",
    "gender": "women",
    "basePrice": 7199,
    "firstImage": "https://cdn.dummyjson.com/product-images/womens-dresses/corset-leather-with-skirt/thumbnail.webp",
    "ratingAverage": 4.2,
    "ratingCount": 269,
    "isFeatured": false,
    "categoryName": "Dresses",
    "discountedPrice": 4463,
    "mrp": 7199,
    "discountPercent": 38,
    "description": "The Corset Leather With Skirt is a bold and edgy ensemble that combines a stylish corset with a matching skirt. Ideal for fashion-forward individuals, it makes a statement at any event.",
    "images": [
      "https://cdn.dummyjson.com/product-images/womens-dresses/corset-leather-with-skirt/1.webp",
      "https://cdn.dummyjson.com/product-images/womens-dresses/corset-leather-with-skirt/2.webp",
      "https://cdn.dummyjson.com/product-images/womens-dresses/corset-leather-with-skirt/3.webp",
      "https://cdn.dummyjson.com/product-images/womens-dresses/corset-leather-with-skirt/4.webp"
    ]
  },
  {
    "id": 13,
    "title": "Black & Brown Slipper",
    "slug": "product-13-black-brown-slipper",
    "brand": "Comfort Trends",
    "gender": "women",
    "basePrice": 1599,
    "firstImage": "https://cdn.dummyjson.com/product-images/womens-shoes/black-&-brown-slipper/thumbnail.webp",
    "ratingAverage": 3.7,
    "ratingCount": 177,
    "isFeatured": false,
    "categoryName": "Sandals & Flats",
    "discountedPrice": 895,
    "mrp": 1599,
    "discountPercent": 44,
    "description": "The Black & Brown Slipper is a comfortable and stylish choice for casual wear. Featuring a blend of black and brown colors, it adds a touch of sophistication to your relaxation.",
    "images": [
      "https://cdn.dummyjson.com/product-images/womens-shoes/black-&-brown-slipper/1.webp",
      "https://cdn.dummyjson.com/product-images/womens-shoes/black-&-brown-slipper/2.webp",
      "https://cdn.dummyjson.com/product-images/womens-shoes/black-&-brown-slipper/3.webp",
      "https://cdn.dummyjson.com/product-images/womens-shoes/black-&-brown-slipper/4.webp"
    ]
  },
  {
    "id": 14,
    "title": "Women Handbag Black",
    "slug": "product-14-women-handbag-black",
    "brand": "Elegance Collection",
    "gender": "women",
    "basePrice": 4799,
    "firstImage": "https://cdn.dummyjson.com/product-images/womens-bags/women-handbag-black/thumbnail.webp",
    "ratingAverage": 4,
    "ratingCount": 155,
    "isFeatured": false,
    "categoryName": "Bags & Wallets",
    "discountedPrice": 3695,
    "mrp": 4799,
    "discountPercent": 23,
    "description": "The Women Handbag in Black is a classic and versatile accessory that complements various outfits. With a timeless black color and functional design, it's a must-have in every woman's wardrobe.",
    "images": [
      "https://cdn.dummyjson.com/product-images/womens-bags/women-handbag-black/1.webp",
      "https://cdn.dummyjson.com/product-images/womens-bags/women-handbag-black/2.webp",
      "https://cdn.dummyjson.com/product-images/womens-bags/women-handbag-black/3.webp"
    ]
  },
  {
    "id": 15,
    "title": "Gray Dress",
    "slug": "product-15-gray-dress",
    "brand": "Style Hub",
    "gender": "women",
    "basePrice": 2799,
    "firstImage": "https://cdn.dummyjson.com/product-images/tops/gray-dress/thumbnail.webp",
    "ratingAverage": 4.5,
    "ratingCount": 275,
    "isFeatured": false,
    "categoryName": "Tops & Tees",
    "discountedPrice": 1875,
    "mrp": 2799,
    "discountPercent": 33,
    "description": "The Gray Dress is a versatile and chic option for various occasions. With a neutral gray color, it can be dressed up or down, making it a wardrobe staple for any fashion-forward individual.",
    "images": [
      "https://cdn.dummyjson.com/product-images/tops/gray-dress/1.webp",
      "https://cdn.dummyjson.com/product-images/tops/gray-dress/2.webp",
      "https://cdn.dummyjson.com/product-images/tops/gray-dress/3.webp",
      "https://cdn.dummyjson.com/product-images/tops/gray-dress/4.webp"
    ]
  },
  {
    "id": 16,
    "title": "Pampi Shoes",
    "slug": "product-16-pampi-shoes",
    "brand": "Pampi",
    "gender": "women",
    "basePrice": 2399,
    "firstImage": "https://cdn.dummyjson.com/product-images/womens-shoes/pampi-shoes/thumbnail.webp",
    "ratingAverage": 3.8,
    "ratingCount": 183,
    "isFeatured": false,
    "categoryName": "Sandals & Flats",
    "discountedPrice": 1535,
    "mrp": 2399,
    "discountPercent": 36,
    "description": "Pampi Shoes offer a blend of comfort and style for everyday use. With a versatile design, they are suitable for various casual occasions, providing a trendy and relaxed look.",
    "images": [
      "https://cdn.dummyjson.com/product-images/womens-shoes/pampi-shoes/1.webp",
      "https://cdn.dummyjson.com/product-images/womens-shoes/pampi-shoes/2.webp",
      "https://cdn.dummyjson.com/product-images/womens-shoes/pampi-shoes/3.webp",
      "https://cdn.dummyjson.com/product-images/womens-shoes/pampi-shoes/4.webp"
    ]
  },
  {
    "id": 17,
    "title": "Tartan Dress",
    "slug": "product-17-tartan-dress",
    "brand": "Style Hub",
    "gender": "women",
    "basePrice": 3199,
    "firstImage": "https://cdn.dummyjson.com/product-images/tops/tartan-dress/thumbnail.webp",
    "ratingAverage": 5,
    "ratingCount": 302,
    "isFeatured": false,
    "categoryName": "Tops & Tees",
    "discountedPrice": 1983,
    "mrp": 3199,
    "discountPercent": 38,
    "description": "The Tartan Dress features a classic tartan pattern, bringing a timeless and sophisticated touch to your wardrobe. Perfect for fall and winter, it adds a hint of traditional charm.",
    "images": [
      "https://cdn.dummyjson.com/product-images/tops/tartan-dress/1.webp",
      "https://cdn.dummyjson.com/product-images/tops/tartan-dress/2.webp",
      "https://cdn.dummyjson.com/product-images/tops/tartan-dress/3.webp",
      "https://cdn.dummyjson.com/product-images/tops/tartan-dress/4.webp"
    ]
  },
  {
    "id": 18,
    "title": "IWC Ingenieur Automatic Steel",
    "slug": "product-18-iwc-ingenieur-automatic-steel",
    "brand": "IWC",
    "gender": "women",
    "basePrice": 399999,
    "firstImage": "https://cdn.dummyjson.com/product-images/womens-watches/iwc-ingenieur-automatic-steel/thumbnail.webp",
    "ratingAverage": 4.4,
    "ratingCount": 40,
    "isFeatured": true,
    "categoryName": "Watches",
    "discountedPrice": 327999,
    "mrp": 399999,
    "discountPercent": 18,
    "description": "The IWC Ingenieur Automatic Steel watch is a durable and sophisticated timepiece. With a stainless steel case and automatic movement, it combines precision and style for watch enthusiasts.",
    "images": [
      "https://cdn.dummyjson.com/product-images/womens-watches/iwc-ingenieur-automatic-steel/1.webp",
      "https://cdn.dummyjson.com/product-images/womens-watches/iwc-ingenieur-automatic-steel/2.webp",
      "https://cdn.dummyjson.com/product-images/womens-watches/iwc-ingenieur-automatic-steel/3.webp"
    ]
  },
  {
    "id": 19,
    "title": "Prada Women Bag",
    "slug": "product-19-prada-women-bag",
    "brand": "Prada",
    "gender": "women",
    "basePrice": 47999,
    "firstImage": "https://cdn.dummyjson.com/product-images/womens-bags/prada-women-bag/thumbnail.webp",
    "ratingAverage": 4.4,
    "ratingCount": 67,
    "isFeatured": false,
    "categoryName": "Bags & Wallets",
    "discountedPrice": 43199,
    "mrp": 47999,
    "discountPercent": 10,
    "description": "The Prada Women Bag is an iconic designer bag that exudes elegance and luxury. Crafted with precision and featuring the Prada logo, it's a statement piece for fashion enthusiasts.",
    "images": [
      "https://cdn.dummyjson.com/product-images/womens-bags/prada-women-bag/1.webp",
      "https://cdn.dummyjson.com/product-images/womens-bags/prada-women-bag/2.webp",
      "https://cdn.dummyjson.com/product-images/womens-bags/prada-women-bag/3.webp"
    ]
  },
  {
    "id": 20,
    "title": "Black Women's Gown",
    "slug": "product-20-black-women-s-gown",
    "brand": "Style Hub",
    "gender": "women",
    "basePrice": 10399,
    "firstImage": "https://cdn.dummyjson.com/product-images/womens-dresses/black-women's-gown/thumbnail.webp",
    "ratingAverage": 3.5,
    "ratingCount": 137,
    "isFeatured": false,
    "categoryName": "Dresses",
    "discountedPrice": 8007,
    "mrp": 10399,
    "discountPercent": 23,
    "description": "The Black Women's Gown is an elegant and timeless evening gown. With a sleek black design, it's perfect for formal events and special occasions, exuding sophistication and style.",
    "images": [
      "https://cdn.dummyjson.com/product-images/womens-dresses/black-women's-gown/1.webp",
      "https://cdn.dummyjson.com/product-images/womens-dresses/black-women's-gown/2.webp",
      "https://cdn.dummyjson.com/product-images/womens-dresses/black-women's-gown/3.webp",
      "https://cdn.dummyjson.com/product-images/womens-dresses/black-women's-gown/4.webp"
    ]
  },
  {
    "id": 21,
    "title": "Blue & Black Check Shirt",
    "slug": "product-21-blue-black-check-shirt",
    "brand": "Fashion Trends",
    "gender": "men",
    "basePrice": 2399,
    "firstImage": "https://cdn.dummyjson.com/product-images/mens-shirts/blue-&-black-check-shirt/thumbnail.webp",
    "ratingAverage": 4.9,
    "ratingCount": 80,
    "isFeatured": false,
    "categoryName": "Shirts",
    "discountedPrice": 1823,
    "mrp": 2399,
    "discountPercent": 24,
    "description": "The Blue & Black Check Shirt is a stylish and comfortable men's shirt featuring a classic check pattern. Made from high-quality fabric, it's suitable for both casual and semi-formal occasions.",
    "images": [
      "https://cdn.dummyjson.com/product-images/mens-shirts/blue-&-black-check-shirt/1.webp",
      "https://cdn.dummyjson.com/product-images/mens-shirts/blue-&-black-check-shirt/2.webp",
      "https://cdn.dummyjson.com/product-images/mens-shirts/blue-&-black-check-shirt/3.webp",
      "https://cdn.dummyjson.com/product-images/mens-shirts/blue-&-black-check-shirt/4.webp"
    ]
  },
  {
    "id": 22,
    "title": "Man Plaid Shirt",
    "slug": "product-22-man-plaid-shirt",
    "brand": "Classic Wear",
    "gender": "men",
    "basePrice": 2799,
    "firstImage": "https://cdn.dummyjson.com/product-images/mens-shirts/man-plaid-shirt/thumbnail.webp",
    "ratingAverage": 4.3,
    "ratingCount": 66,
    "isFeatured": false,
    "categoryName": "Shirts",
    "discountedPrice": 1931,
    "mrp": 2799,
    "discountPercent": 31,
    "description": "The Man Plaid Shirt is a timeless and versatile men's shirt with a classic plaid pattern. Its comfortable fit and casual style make it a wardrobe essential for various occasions.",
    "images": [
      "https://cdn.dummyjson.com/product-images/mens-shirts/man-plaid-shirt/1.webp",
      "https://cdn.dummyjson.com/product-images/mens-shirts/man-plaid-shirt/2.webp",
      "https://cdn.dummyjson.com/product-images/mens-shirts/man-plaid-shirt/3.webp",
      "https://cdn.dummyjson.com/product-images/mens-shirts/man-plaid-shirt/4.webp"
    ]
  },
  {
    "id": 23,
    "title": "Rolex Cellini Moonphase",
    "slug": "product-23-rolex-cellini-moonphase",
    "brand": "Rolex",
    "gender": "men",
    "basePrice": 1039999,
    "firstImage": "https://cdn.dummyjson.com/product-images/mens-watches/rolex-cellini-moonphase/thumbnail.webp",
    "ratingAverage": 4,
    "ratingCount": 274,
    "isFeatured": false,
    "categoryName": "Watches",
    "discountedPrice": 904799,
    "mrp": 1039999,
    "discountPercent": 13,
    "description": "The Rolex Cellini Moonphase is a masterpiece of horology, featuring a moon phase complication and exquisite design. It reflects Rolex's commitment to precision and elegance.",
    "images": [
      "https://cdn.dummyjson.com/product-images/mens-watches/rolex-cellini-moonphase/1.webp",
      "https://cdn.dummyjson.com/product-images/mens-watches/rolex-cellini-moonphase/2.webp",
      "https://cdn.dummyjson.com/product-images/mens-watches/rolex-cellini-moonphase/3.webp"
    ]
  },
  {
    "id": 24,
    "title": "Sports Sneakers Off White Red",
    "slug": "product-24-sports-sneakers-off-white-red",
    "brand": "Off White",
    "gender": "men",
    "basePrice": 8799,
    "firstImage": "https://cdn.dummyjson.com/product-images/mens-shoes/sports-sneakers-off-white-red/thumbnail.webp",
    "ratingAverage": 3.8,
    "ratingCount": 73,
    "isFeatured": false,
    "categoryName": "Sneakers",
    "discountedPrice": 6511,
    "mrp": 8799,
    "discountPercent": 26,
    "description": "Another variant of the Sports Sneakers in Off White Red, featuring a unique design. These sneakers offer style and comfort for casual occasions.",
    "images": [
      "https://cdn.dummyjson.com/product-images/mens-shoes/sports-sneakers-off-white-red/1.webp",
      "https://cdn.dummyjson.com/product-images/mens-shoes/sports-sneakers-off-white-red/2.webp",
      "https://cdn.dummyjson.com/product-images/mens-shoes/sports-sneakers-off-white-red/3.webp",
      "https://cdn.dummyjson.com/product-images/mens-shoes/sports-sneakers-off-white-red/4.webp"
    ]
  },
  {
    "id": 25,
    "title": "Puma Future Rider Trainers",
    "slug": "product-25-puma-future-rider-trainers",
    "brand": "Puma",
    "gender": "men",
    "basePrice": 7199,
    "firstImage": "https://cdn.dummyjson.com/product-images/mens-shoes/puma-future-rider-trainers/thumbnail.webp",
    "ratingAverage": 4.8,
    "ratingCount": 294,
    "isFeatured": false,
    "categoryName": "Sneakers",
    "discountedPrice": 4535,
    "mrp": 7199,
    "discountPercent": 37,
    "description": "The Puma Future Rider Trainers offer a blend of retro style and modern comfort. Perfect for casual wear, these trainers provide a fashionable and comfortable option for everyday use.",
    "images": [
      "https://cdn.dummyjson.com/product-images/mens-shoes/puma-future-rider-trainers/1.webp",
      "https://cdn.dummyjson.com/product-images/mens-shoes/puma-future-rider-trainers/2.webp",
      "https://cdn.dummyjson.com/product-images/mens-shoes/puma-future-rider-trainers/3.webp",
      "https://cdn.dummyjson.com/product-images/mens-shoes/puma-future-rider-trainers/4.webp"
    ]
  },
  {
    "id": 26,
    "title": "Rolex Submariner Watch",
    "slug": "product-26-rolex-submariner-watch",
    "brand": "Rolex",
    "gender": "men",
    "basePrice": 1119999,
    "firstImage": "https://cdn.dummyjson.com/product-images/mens-watches/rolex-submariner-watch/thumbnail.webp",
    "ratingAverage": 4.9,
    "ratingCount": 285,
    "isFeatured": false,
    "categoryName": "Watches",
    "discountedPrice": 615999,
    "mrp": 1119999,
    "discountPercent": 45,
    "description": "The Rolex Submariner is a legendary dive watch with a rich history. Known for its durability and water resistance, it's a symbol of adventure and exploration.",
    "images": [
      "https://cdn.dummyjson.com/product-images/mens-watches/rolex-submariner-watch/1.webp",
      "https://cdn.dummyjson.com/product-images/mens-watches/rolex-submariner-watch/2.webp",
      "https://cdn.dummyjson.com/product-images/mens-watches/rolex-submariner-watch/3.webp"
    ]
  },
  {
    "id": 27,
    "title": "Nike Air Jordan 1 Red And Black",
    "slug": "product-27-nike-air-jordan-1-red-and-black",
    "brand": "Nike",
    "gender": "men",
    "basePrice": 11999,
    "firstImage": "https://cdn.dummyjson.com/product-images/mens-shoes/nike-air-jordan-1-red-and-black/thumbnail.webp",
    "ratingAverage": 4,
    "ratingCount": 195,
    "isFeatured": true,
    "categoryName": "Sneakers",
    "discountedPrice": 7799,
    "mrp": 11999,
    "discountPercent": 35,
    "description": "The Nike Air Jordan 1 in Red and Black is an iconic basketball sneaker known for its stylish design and high-performance features, making it a favorite among sneaker enthusiasts and athletes.",
    "images": [
      "https://cdn.dummyjson.com/product-images/mens-shoes/nike-air-jordan-1-red-and-black/1.webp",
      "https://cdn.dummyjson.com/product-images/mens-shoes/nike-air-jordan-1-red-and-black/2.webp",
      "https://cdn.dummyjson.com/product-images/mens-shoes/nike-air-jordan-1-red-and-black/3.webp",
      "https://cdn.dummyjson.com/product-images/mens-shoes/nike-air-jordan-1-red-and-black/4.webp"
    ]
  },
  {
    "id": 28,
    "title": "Gigabyte Aorus Men Tshirt",
    "slug": "product-28-gigabyte-aorus-men-tshirt",
    "brand": "Gigabyte",
    "gender": "men",
    "basePrice": 1999,
    "firstImage": "https://cdn.dummyjson.com/product-images/mens-shirts/gigabyte-aorus-men-tshirt/thumbnail.webp",
    "ratingAverage": 4.8,
    "ratingCount": 292,
    "isFeatured": false,
    "categoryName": "Shirts",
    "discountedPrice": 1759,
    "mrp": 1999,
    "discountPercent": 12,
    "description": "The Gigabyte Aorus Men Tshirt is a cool and casual shirt for gaming enthusiasts. With the Aorus logo and sleek design, it's perfect for expressing your gaming style.",
    "images": [
      "https://cdn.dummyjson.com/product-images/mens-shirts/gigabyte-aorus-men-tshirt/1.webp",
      "https://cdn.dummyjson.com/product-images/mens-shirts/gigabyte-aorus-men-tshirt/2.webp",
      "https://cdn.dummyjson.com/product-images/mens-shirts/gigabyte-aorus-men-tshirt/3.webp",
      "https://cdn.dummyjson.com/product-images/mens-shirts/gigabyte-aorus-men-tshirt/4.webp"
    ]
  },
  {
    "id": 29,
    "title": "Brown Leather Belt Watch",
    "slug": "product-29-brown-leather-belt-watch",
    "brand": "Fashion Timepieces",
    "gender": "men",
    "basePrice": 7199,
    "firstImage": "https://images.unsplash.com/photo-1524805444758-089113d48a6d?w=400",
    "ratingAverage": 4.3,
    "ratingCount": 275,
    "isFeatured": false,
    "categoryName": "Watches",
    "discountedPrice": 4895,
    "mrp": 7199,
    "discountPercent": 32,
    "description": "The Brown Leather Belt Watch is a stylish timepiece with a classic design. Featuring a genuine leather strap and a sleek dial, it adds a touch of sophistication to your look.",
    "images": [
      "https://images.unsplash.com/photo-1524805444758-089113d48a6d?w=400",
      "https://images.unsplash.com/photo-1522312346375-d1a52e2b99b3?w=400",
      "https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=400"
    ]
  },
  {
    "id": 30,
    "title": "Man Short Sleeve Shirt",
    "slug": "product-30-man-short-sleeve-shirt",
    "brand": "Casual Comfort",
    "gender": "men",
    "basePrice": 1599,
    "firstImage": "https://cdn.dummyjson.com/product-images/mens-shirts/man-short-sleeve-shirt/thumbnail.webp",
    "ratingAverage": 5,
    "ratingCount": 152,
    "isFeatured": false,
    "categoryName": "Shirts",
    "discountedPrice": 1407,
    "mrp": 1599,
    "discountPercent": 12,
    "description": "The Man Short Sleeve Shirt is a breezy and stylish option for warm days. With a comfortable fit and short sleeves, it's perfect for a laid-back yet polished look.",
    "images": [
      "https://cdn.dummyjson.com/product-images/mens-shirts/man-short-sleeve-shirt/1.webp",
      "https://cdn.dummyjson.com/product-images/mens-shirts/man-short-sleeve-shirt/2.webp",
      "https://cdn.dummyjson.com/product-images/mens-shirts/man-short-sleeve-shirt/3.webp",
      "https://cdn.dummyjson.com/product-images/mens-shirts/man-short-sleeve-shirt/4.webp"
    ]
  },
  {
    "id": 31,
    "title": "Men Check Shirt",
    "slug": "product-31-men-check-shirt",
    "brand": "Urban Chic",
    "gender": "men",
    "basePrice": 2239,
    "firstImage": "https://cdn.dummyjson.com/product-images/mens-shirts/men-check-shirt/thumbnail.webp",
    "ratingAverage": 3.5,
    "ratingCount": 228,
    "isFeatured": true,
    "categoryName": "Shirts",
    "discountedPrice": 1186,
    "mrp": 2239,
    "discountPercent": 47,
    "description": "The Men Check Shirt is a classic and versatile shirt featuring a stylish check pattern. Suitable for various occasions, it adds a smart and polished touch to your wardrobe.",
    "images": [
      "https://cdn.dummyjson.com/product-images/mens-shirts/men-check-shirt/1.webp",
      "https://cdn.dummyjson.com/product-images/mens-shirts/men-check-shirt/2.webp",
      "https://cdn.dummyjson.com/product-images/mens-shirts/men-check-shirt/3.webp",
      "https://cdn.dummyjson.com/product-images/mens-shirts/men-check-shirt/4.webp"
    ]
  },
  {
    "id": 32,
    "title": "Rolex Datejust",
    "slug": "product-32-rolex-datejust",
    "brand": "Rolex",
    "gender": "men",
    "basePrice": 879999,
    "firstImage": "https://cdn.dummyjson.com/product-images/mens-watches/rolex-datejust/thumbnail.webp",
    "ratingAverage": 4.5,
    "ratingCount": 25,
    "isFeatured": false,
    "categoryName": "Watches",
    "discountedPrice": 589599,
    "mrp": 879999,
    "discountPercent": 33,
    "description": "The Rolex Datejust is an iconic and versatile timepiece with a date window. Known for its timeless design and reliability, it's a symbol of Rolex's watchmaking excellence.",
    "images": [
      "https://cdn.dummyjson.com/product-images/mens-watches/rolex-datejust/1.webp",
      "https://cdn.dummyjson.com/product-images/mens-watches/rolex-datejust/2.webp",
      "https://cdn.dummyjson.com/product-images/mens-watches/rolex-datejust/3.webp"
    ]
  },
  {
    "id": 33,
    "title": "Sports Sneakers Off White & Red",
    "slug": "product-33-sports-sneakers-off-white-red",
    "brand": "Off White",
    "gender": "men",
    "basePrice": 9599,
    "firstImage": "https://cdn.dummyjson.com/product-images/mens-shoes/sports-sneakers-off-white-&-red/thumbnail.webp",
    "ratingAverage": 3.7,
    "ratingCount": 201,
    "isFeatured": false,
    "categoryName": "Sneakers",
    "discountedPrice": 7871,
    "mrp": 9599,
    "discountPercent": 18,
    "description": "The Sports Sneakers in Off White and Red combine style and functionality, making them a fashionable choice for sports enthusiasts. The red and off-white color combination adds a bold and energetic touch.",
    "images": [
      "https://cdn.dummyjson.com/product-images/mens-shoes/sports-sneakers-off-white-&-red/1.webp",
      "https://cdn.dummyjson.com/product-images/mens-shoes/sports-sneakers-off-white-&-red/2.webp",
      "https://cdn.dummyjson.com/product-images/mens-shoes/sports-sneakers-off-white-&-red/3.webp",
      "https://cdn.dummyjson.com/product-images/mens-shoes/sports-sneakers-off-white-&-red/4.webp"
    ]
  },
  {
    "id": 34,
    "title": "Longines Master Collection",
    "slug": "product-34-longines-master-collection",
    "brand": "Longines",
    "gender": "men",
    "basePrice": 119999,
    "firstImage": "https://cdn.dummyjson.com/product-images/mens-watches/longines-master-collection/thumbnail.webp",
    "ratingAverage": 3.9,
    "ratingCount": 61,
    "isFeatured": false,
    "categoryName": "Watches",
    "discountedPrice": 75599,
    "mrp": 119999,
    "discountPercent": 37,
    "description": "The Longines Master Collection is an elegant and refined watch known for its precision and craftsmanship. With a timeless design, it's a symbol of luxury and sophistication.",
    "images": [
      "https://cdn.dummyjson.com/product-images/mens-watches/longines-master-collection/1.webp",
      "https://cdn.dummyjson.com/product-images/mens-watches/longines-master-collection/2.webp",
      "https://cdn.dummyjson.com/product-images/mens-watches/longines-master-collection/3.webp"
    ]
  },
  {
    "id": 35,
    "title": "Rolex Cellini Date Black Dial",
    "slug": "product-35-rolex-cellini-date-black-dial",
    "brand": "Rolex",
    "gender": "men",
    "basePrice": 719999,
    "firstImage": "https://cdn.dummyjson.com/product-images/mens-watches/rolex-cellini-date-black-dial/thumbnail.webp",
    "ratingAverage": 3.9,
    "ratingCount": 299,
    "isFeatured": false,
    "categoryName": "Watches",
    "discountedPrice": 467999,
    "mrp": 719999,
    "discountPercent": 35,
    "description": "The Rolex Cellini Date with Black Dial is a classic and prestigious watch. With a black dial and date complication, it exudes sophistication and is a symbol of Rolex's heritage.",
    "images": [
      "https://cdn.dummyjson.com/product-images/mens-watches/rolex-cellini-date-black-dial/1.webp",
      "https://cdn.dummyjson.com/product-images/mens-watches/rolex-cellini-date-black-dial/2.webp",
      "https://cdn.dummyjson.com/product-images/mens-watches/rolex-cellini-date-black-dial/3.webp"
    ]
  },
  {
    "id": 36,
    "title": "Nike Baseball Cleats",
    "slug": "product-36-nike-baseball-cleats",
    "brand": "Nike",
    "gender": "men",
    "basePrice": 6399,
    "firstImage": "https://cdn.dummyjson.com/product-images/mens-shoes/nike-baseball-cleats/thumbnail.webp",
    "ratingAverage": 4.9,
    "ratingCount": 85,
    "isFeatured": false,
    "categoryName": "Sneakers",
    "discountedPrice": 3647,
    "mrp": 6399,
    "discountPercent": 43,
    "description": "Nike Baseball Cleats are designed for maximum traction and performance on the baseball field. They provide stability and support for players during games and practices.",
    "images": [
      "https://cdn.dummyjson.com/product-images/mens-shoes/nike-baseball-cleats/1.webp",
      "https://cdn.dummyjson.com/product-images/mens-shoes/nike-baseball-cleats/2.webp",
      "https://cdn.dummyjson.com/product-images/mens-shoes/nike-baseball-cleats/3.webp",
      "https://cdn.dummyjson.com/product-images/mens-shoes/nike-baseball-cleats/4.webp"
    ]
  },
  {
    "id": 37,
    "title": "Blue & Black Check Shirt",
    "slug": "product-37-blue-black-check-shirt",
    "brand": "Fashion Trends",
    "gender": "men",
    "basePrice": 2399,
    "firstImage": "https://cdn.dummyjson.com/product-images/mens-shirts/blue-&-black-check-shirt/thumbnail.webp",
    "ratingAverage": 4.8,
    "ratingCount": 154,
    "isFeatured": false,
    "categoryName": "Shirts",
    "discountedPrice": 2063,
    "mrp": 2399,
    "discountPercent": 14,
    "description": "The Blue & Black Check Shirt is a stylish and comfortable men's shirt featuring a classic check pattern. Made from high-quality fabric, it's suitable for both casual and semi-formal occasions.",
    "images": [
      "https://cdn.dummyjson.com/product-images/mens-shirts/blue-&-black-check-shirt/1.webp",
      "https://cdn.dummyjson.com/product-images/mens-shirts/blue-&-black-check-shirt/2.webp",
      "https://cdn.dummyjson.com/product-images/mens-shirts/blue-&-black-check-shirt/3.webp",
      "https://cdn.dummyjson.com/product-images/mens-shirts/blue-&-black-check-shirt/4.webp"
    ]
  },
  {
    "id": 38,
    "title": "Man Plaid Shirt",
    "slug": "product-38-man-plaid-shirt",
    "brand": "Classic Wear",
    "gender": "men",
    "basePrice": 2799,
    "firstImage": "https://cdn.dummyjson.com/product-images/mens-shirts/man-plaid-shirt/thumbnail.webp",
    "ratingAverage": 3.8,
    "ratingCount": 208,
    "isFeatured": true,
    "categoryName": "Shirts",
    "discountedPrice": 1511,
    "mrp": 2799,
    "discountPercent": 46,
    "description": "The Man Plaid Shirt is a timeless and versatile men's shirt with a classic plaid pattern. Its comfortable fit and casual style make it a wardrobe essential for various occasions.",
    "images": [
      "https://cdn.dummyjson.com/product-images/mens-shirts/man-plaid-shirt/1.webp",
      "https://cdn.dummyjson.com/product-images/mens-shirts/man-plaid-shirt/2.webp",
      "https://cdn.dummyjson.com/product-images/mens-shirts/man-plaid-shirt/3.webp",
      "https://cdn.dummyjson.com/product-images/mens-shirts/man-plaid-shirt/4.webp"
    ]
  },
  {
    "id": 39,
    "title": "Rolex Cellini Moonphase",
    "slug": "product-39-rolex-cellini-moonphase",
    "brand": "Rolex",
    "gender": "men",
    "basePrice": 1039999,
    "firstImage": "https://cdn.dummyjson.com/product-images/mens-watches/rolex-cellini-moonphase/thumbnail.webp",
    "ratingAverage": 4,
    "ratingCount": 218,
    "isFeatured": false,
    "categoryName": "Watches",
    "discountedPrice": 821599,
    "mrp": 1039999,
    "discountPercent": 21,
    "description": "The Rolex Cellini Moonphase is a masterpiece of horology, featuring a moon phase complication and exquisite design. It reflects Rolex's commitment to precision and elegance.",
    "images": [
      "https://cdn.dummyjson.com/product-images/mens-watches/rolex-cellini-moonphase/1.webp",
      "https://cdn.dummyjson.com/product-images/mens-watches/rolex-cellini-moonphase/2.webp",
      "https://cdn.dummyjson.com/product-images/mens-watches/rolex-cellini-moonphase/3.webp"
    ]
  },
  {
    "id": 40,
    "title": "Sports Sneakers Off White Red",
    "slug": "product-40-sports-sneakers-off-white-red",
    "brand": "Off White",
    "gender": "men",
    "basePrice": 8799,
    "firstImage": "https://cdn.dummyjson.com/product-images/mens-shoes/sports-sneakers-off-white-red/thumbnail.webp",
    "ratingAverage": 3.6,
    "ratingCount": 37,
    "isFeatured": false,
    "categoryName": "Sneakers",
    "discountedPrice": 4575,
    "mrp": 8799,
    "discountPercent": 48,
    "description": "Another variant of the Sports Sneakers in Off White Red, featuring a unique design. These sneakers offer style and comfort for casual occasions.",
    "images": [
      "https://cdn.dummyjson.com/product-images/mens-shoes/sports-sneakers-off-white-red/1.webp",
      "https://cdn.dummyjson.com/product-images/mens-shoes/sports-sneakers-off-white-red/2.webp",
      "https://cdn.dummyjson.com/product-images/mens-shoes/sports-sneakers-off-white-red/3.webp",
      "https://cdn.dummyjson.com/product-images/mens-shoes/sports-sneakers-off-white-red/4.webp"
    ]
  },
  {
    "id": 41,
    "title": "Sunglasses",
    "slug": "product-41-sunglasses",
    "brand": "Fashion Shades",
    "gender": "unisex",
    "basePrice": 1839,
    "firstImage": "https://cdn.dummyjson.com/product-images/sunglasses/sunglasses/thumbnail.webp",
    "ratingAverage": 4.5,
    "ratingCount": 116,
    "isFeatured": true,
    "categoryName": "Sunglasses",
    "discountedPrice": 1342,
    "mrp": 1839,
    "discountPercent": 27,
    "description": "The Sunglasses offer a classic and simple design with a focus on functionality. These sunglasses provide essential UV protection while maintaining a timeless look.",
    "images": [
      "https://cdn.dummyjson.com/product-images/sunglasses/sunglasses/1.webp",
      "https://cdn.dummyjson.com/product-images/sunglasses/sunglasses/2.webp",
      "https://cdn.dummyjson.com/product-images/sunglasses/sunglasses/3.webp"
    ]
  },
  {
    "id": 42,
    "title": "Party Glasses",
    "slug": "product-42-party-glasses",
    "brand": "Fashion Fun",
    "gender": "unisex",
    "basePrice": 1599,
    "firstImage": "https://cdn.dummyjson.com/product-images/sunglasses/party-glasses/thumbnail.webp",
    "ratingAverage": 4,
    "ratingCount": 163,
    "isFeatured": false,
    "categoryName": "Sunglasses",
    "discountedPrice": 1151,
    "mrp": 1599,
    "discountPercent": 28,
    "description": "The Party Glasses are designed to add flair to your party outfit. With unique shapes or colorful frames, they're perfect for adding a playful touch to your look during celebrations.",
    "images": [
      "https://cdn.dummyjson.com/product-images/sunglasses/party-glasses/1.webp",
      "https://cdn.dummyjson.com/product-images/sunglasses/party-glasses/2.webp",
      "https://cdn.dummyjson.com/product-images/sunglasses/party-glasses/3.webp"
    ]
  },
  {
    "id": 43,
    "title": "Green and Black Glasses",
    "slug": "product-43-green-and-black-glasses",
    "brand": "Fashion Shades",
    "gender": "unisex",
    "basePrice": 2799,
    "firstImage": "https://cdn.dummyjson.com/product-images/sunglasses/green-and-black-glasses/thumbnail.webp",
    "ratingAverage": 4.2,
    "ratingCount": 122,
    "isFeatured": false,
    "categoryName": "Sunglasses",
    "discountedPrice": 1819,
    "mrp": 2799,
    "discountPercent": 35,
    "description": "The Green and Black Glasses feature a bold combination of green and black colors, adding a touch of vibrancy to your eyewear collection. They are both stylish and eye-catching.",
    "images": [
      "https://cdn.dummyjson.com/product-images/sunglasses/green-and-black-glasses/1.webp",
      "https://cdn.dummyjson.com/product-images/sunglasses/green-and-black-glasses/2.webp",
      "https://cdn.dummyjson.com/product-images/sunglasses/green-and-black-glasses/3.webp"
    ]
  },
  {
    "id": 44,
    "title": "Classic Sun Glasses",
    "slug": "product-44-classic-sun-glasses",
    "brand": "Fashion Shades",
    "gender": "unisex",
    "basePrice": 1999,
    "firstImage": "https://cdn.dummyjson.com/product-images/sunglasses/classic-sun-glasses/thumbnail.webp",
    "ratingAverage": 4.2,
    "ratingCount": 23,
    "isFeatured": false,
    "categoryName": "Sunglasses",
    "discountedPrice": 1219,
    "mrp": 1999,
    "discountPercent": 39,
    "description": "The Classic Sun Glasses offer a timeless design with a neutral frame and UV-protected lenses. These sunglasses are versatile and suitable for various occasions.",
    "images": [
      "https://cdn.dummyjson.com/product-images/sunglasses/classic-sun-glasses/1.webp",
      "https://cdn.dummyjson.com/product-images/sunglasses/classic-sun-glasses/2.webp",
      "https://cdn.dummyjson.com/product-images/sunglasses/classic-sun-glasses/3.webp"
    ]
  },
  {
    "id": 45,
    "title": "Black Sun Glasses",
    "slug": "product-45-black-sun-glasses",
    "brand": "Fashion Shades",
    "gender": "unisex",
    "basePrice": 2399,
    "firstImage": "https://cdn.dummyjson.com/product-images/sunglasses/black-sun-glasses/thumbnail.webp",
    "ratingAverage": 3.6,
    "ratingCount": 67,
    "isFeatured": false,
    "categoryName": "Sunglasses",
    "discountedPrice": 1919,
    "mrp": 2399,
    "discountPercent": 20,
    "description": "The Black Sun Glasses are a classic and stylish choice, featuring a sleek black frame and tinted lenses. They provide both UV protection and a fashionable look.",
    "images": [
      "https://cdn.dummyjson.com/product-images/sunglasses/black-sun-glasses/1.webp",
      "https://cdn.dummyjson.com/product-images/sunglasses/black-sun-glasses/2.webp",
      "https://cdn.dummyjson.com/product-images/sunglasses/black-sun-glasses/3.webp"
    ]
  },
  {
    "id": 46,
    "title": "Sunglasses",
    "slug": "product-46-sunglasses",
    "brand": "Fashion Shades",
    "gender": "unisex",
    "basePrice": 1839,
    "firstImage": "https://cdn.dummyjson.com/product-images/sunglasses/sunglasses/thumbnail.webp",
    "ratingAverage": 4.7,
    "ratingCount": 250,
    "isFeatured": false,
    "categoryName": "Sunglasses",
    "discountedPrice": 1544,
    "mrp": 1839,
    "discountPercent": 16,
    "description": "The Sunglasses offer a classic and simple design with a focus on functionality. These sunglasses provide essential UV protection while maintaining a timeless look.",
    "images": [
      "https://cdn.dummyjson.com/product-images/sunglasses/sunglasses/1.webp",
      "https://cdn.dummyjson.com/product-images/sunglasses/sunglasses/2.webp",
      "https://cdn.dummyjson.com/product-images/sunglasses/sunglasses/3.webp"
    ]
  },
  {
    "id": 47,
    "title": "Party Glasses",
    "slug": "product-47-party-glasses",
    "brand": "Fashion Fun",
    "gender": "unisex",
    "basePrice": 1599,
    "firstImage": "https://cdn.dummyjson.com/product-images/sunglasses/party-glasses/thumbnail.webp",
    "ratingAverage": 4.9,
    "ratingCount": 207,
    "isFeatured": true,
    "categoryName": "Sunglasses",
    "discountedPrice": 975,
    "mrp": 1599,
    "discountPercent": 39,
    "description": "The Party Glasses are designed to add flair to your party outfit. With unique shapes or colorful frames, they're perfect for adding a playful touch to your look during celebrations.",
    "images": [
      "https://cdn.dummyjson.com/product-images/sunglasses/party-glasses/1.webp",
      "https://cdn.dummyjson.com/product-images/sunglasses/party-glasses/2.webp",
      "https://cdn.dummyjson.com/product-images/sunglasses/party-glasses/3.webp"
    ]
  },
  {
    "id": 48,
    "title": "Green and Black Glasses",
    "slug": "product-48-green-and-black-glasses",
    "brand": "Fashion Shades",
    "gender": "unisex",
    "basePrice": 2799,
    "firstImage": "https://cdn.dummyjson.com/product-images/sunglasses/green-and-black-glasses/thumbnail.webp",
    "ratingAverage": 4.2,
    "ratingCount": 21,
    "isFeatured": false,
    "categoryName": "Sunglasses",
    "discountedPrice": 1679,
    "mrp": 2799,
    "discountPercent": 40,
    "description": "The Green and Black Glasses feature a bold combination of green and black colors, adding a touch of vibrancy to your eyewear collection. They are both stylish and eye-catching.",
    "images": [
      "https://cdn.dummyjson.com/product-images/sunglasses/green-and-black-glasses/1.webp",
      "https://cdn.dummyjson.com/product-images/sunglasses/green-and-black-glasses/2.webp",
      "https://cdn.dummyjson.com/product-images/sunglasses/green-and-black-glasses/3.webp"
    ]
  },
  {
    "id": 49,
    "title": "Classic Sun Glasses",
    "slug": "product-49-classic-sun-glasses",
    "brand": "Fashion Shades",
    "gender": "unisex",
    "basePrice": 1999,
    "firstImage": "https://cdn.dummyjson.com/product-images/sunglasses/classic-sun-glasses/thumbnail.webp",
    "ratingAverage": 4.6,
    "ratingCount": 158,
    "isFeatured": false,
    "categoryName": "Sunglasses",
    "discountedPrice": 1739,
    "mrp": 1999,
    "discountPercent": 13,
    "description": "The Classic Sun Glasses offer a timeless design with a neutral frame and UV-protected lenses. These sunglasses are versatile and suitable for various occasions.",
    "images": [
      "https://cdn.dummyjson.com/product-images/sunglasses/classic-sun-glasses/1.webp",
      "https://cdn.dummyjson.com/product-images/sunglasses/classic-sun-glasses/2.webp",
      "https://cdn.dummyjson.com/product-images/sunglasses/classic-sun-glasses/3.webp"
    ]
  },
  {
    "id": 50,
    "title": "Black Sun Glasses",
    "slug": "product-50-black-sun-glasses",
    "brand": "Fashion Shades",
    "gender": "unisex",
    "basePrice": 2399,
    "firstImage": "https://cdn.dummyjson.com/product-images/sunglasses/black-sun-glasses/thumbnail.webp",
    "ratingAverage": 3.5,
    "ratingCount": 59,
    "isFeatured": false,
    "categoryName": "Sunglasses",
    "discountedPrice": 1415,
    "mrp": 2399,
    "discountPercent": 41,
    "description": "The Black Sun Glasses are a classic and stylish choice, featuring a sleek black frame and tinted lenses. They provide both UV protection and a fashionable look.",
    "images": [
      "https://cdn.dummyjson.com/product-images/sunglasses/black-sun-glasses/1.webp",
      "https://cdn.dummyjson.com/product-images/sunglasses/black-sun-glasses/2.webp",
      "https://cdn.dummyjson.com/product-images/sunglasses/black-sun-glasses/3.webp"
    ]
  }
].map((p: any) => ({
  id: p.id,
  title: p.title,
  slug: p.slug,
  description: p.description || `Premium quality ${p.title.toLowerCase()} from ${p.brand}. Crafted with attention to detail and designed for modern fashion enthusiasts.`,
  brand: p.brand,
  gender: p.gender,
  material: 'Premium Fabric',
  basePrice: p.basePrice,
  ratingAverage: p.ratingAverage,
  ratingCount: p.ratingCount,
  isFeatured: p.isFeatured,
  category: { id: 1, name: p.categoryName, slug: p.categoryName.toLowerCase().replace(/ /g, '-'), parentId: undefined },
  images: p.images.map((url: string, i: number) => ({ id: i + 1, url: url, displayOrder: i })),
  variants: [
    { id: p.id * 10 + 1, sku: `SKU-${p.id}-S`, color: 'Black', colorHex: '#000000', size: 'S', price: p.discountedPrice || p.basePrice, mrp: p.mrp || p.basePrice, stock: 25 },
    { id: p.id * 10 + 2, sku: `SKU-${p.id}-M`, color: 'Black', colorHex: '#000000', size: 'M', price: p.discountedPrice || p.basePrice, mrp: p.mrp || p.basePrice, stock: 40 },
    { id: p.id * 10 + 3, sku: `SKU-${p.id}-L`, color: 'Black', colorHex: '#000000', size: 'L', price: p.discountedPrice || p.basePrice, mrp: p.mrp || p.basePrice, stock: 30 },
  ],
  reviews: [
    { id: 1, rating: 5, title: 'Excellent quality!', comment: 'Absolutely love this product. The material feels premium and the fit is perfect.', userName: 'Priya S.', isVerifiedPurchase: true, createdAt: '2026-06-10T10:00:00Z' },
  ]
}));
