services:
  # ----------------------------------------
  # 1. Backend Web Service (Docker)
  # ----------------------------------------
  - type: web
    name: ecommerce-api
    env: docker
    region: ohio
    plan: free
    dockerContext: backend
    dockerfilePath: backend/Dockerfile
    envVars:
      - key: ConnectionStrings__DefaultConnection
        sync: false
      - key: Jwt__Secret
        sync: false
      - key: Jwt__Issuer
        value: FashionStoreAPI
      - key: Jwt__Audience
        value: FashionStoreApp
      - key: Razorpay__KeyId
        sync: false
      - key: Razorpay__KeySecret
        sync: false

  # ----------------------------------------
  # 2. Frontend Static Site (Angular)
  # ----------------------------------------
  - type: web
    name: ecommerce-ui
    env: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist/frontend/browser
    envVars:
      - key: NODE_VERSION
        value: 20
